// <auto-generated />
using System;
using ImdbAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ImdbAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211005163349_addCoverImageUpdate")]
    partial class addCoverImageUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ImdbAPI.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Antonio",
                            Surname = "Banderas"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Leonardo",
                            Surname = "DiCaprio"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Daniel",
                            Surname = "Craig"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Robert",
                            Surname = "Downey Jr"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Vin",
                            Surname = "Diesel"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Morgan",
                            Surname = "Freeman"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Nikola",
                            Surname = "Kojo"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Mustafa",
                            Surname = "Nadarević"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dejan",
                            Surname = "Kotiga"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Kevin",
                            Surname = "Hart"
                        });
                });

            modelBuilder.Entity("ImdbAPI.Models.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<string>("CoverImage")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("GroupType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Medias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 8.4000000000000004,
                            CoverImage = "movie.jpg",
                            Description = "ovo je desc",
                            GroupType = 1,
                            ReleaseDate = new DateTime(2011, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ironman 1"
                        },
                        new
                        {
                            Id = 2,
                            AverageRating = 9.0999999999999996,
                            CoverImage = "movie.jpg",
                            Description = "ovo je desc",
                            GroupType = 1,
                            ReleaseDate = new DateTime(2000, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ironman 2"
                        },
                        new
                        {
                            Id = 3,
                            AverageRating = 8.0999999999999996,
                            CoverImage = "movie.jpg",
                            Description = "ovo je desc",
                            GroupType = 1,
                            ReleaseDate = new DateTime(2005, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ironman 3"
                        },
                        new
                        {
                            Id = 4,
                            AverageRating = 9.5,
                            CoverImage = "movie.jpg",
                            Description = "ovo je desc",
                            GroupType = 1,
                            ReleaseDate = new DateTime(2002, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fast and furious"
                        },
                        new
                        {
                            Id = 5,
                            AverageRating = 10.0,
                            CoverImage = "movie.jpg",
                            Description = "ovo je desc",
                            GroupType = 1,
                            ReleaseDate = new DateTime(2018, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avengers"
                        },
                        new
                        {
                            Id = 6,
                            AverageRating = 7.5,
                            CoverImage = "movie.jpg",
                            Description = "ovo je desc",
                            GroupType = 1,
                            ReleaseDate = new DateTime(1990, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "James Bond"
                        },
                        new
                        {
                            Id = 7,
                            AverageRating = 9.3000000000000007,
                            CoverImage = "movie.jpg",
                            Description = "ovo je desc",
                            GroupType = 1,
                            ReleaseDate = new DateTime(1995, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lord of rings"
                        },
                        new
                        {
                            Id = 8,
                            AverageRating = 8.9000000000000004,
                            CoverImage = "movie.jpeg",
                            Description = "ovo je desc",
                            GroupType = 1,
                            ReleaseDate = new DateTime(1998, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hobit"
                        },
                        new
                        {
                            Id = 9,
                            AverageRating = 9.6999999999999993,
                            CoverImage = "movie.jpg",
                            Description = "ovo je desc",
                            GroupType = 1,
                            ReleaseDate = new DateTime(2016, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wolf of Wall Street"
                        },
                        new
                        {
                            Id = 10,
                            AverageRating = 9.1999999999999993,
                            CoverImage = "movie.jpg",
                            Description = "ovo je desc",
                            GroupType = 1,
                            ReleaseDate = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jumanji"
                        },
                        new
                        {
                            Id = 11,
                            AverageRating = 9.9000000000000004,
                            CoverImage = "movie.jpg",
                            Description = "ovo je desc",
                            GroupType = 1,
                            ReleaseDate = new DateTime(1989, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Swanshank Redemption"
                        },
                        new
                        {
                            Id = 12,
                            AverageRating = 9.5999999999999996,
                            CoverImage = "movie.jpg",
                            Description = "ovo je desc",
                            GroupType = 1,
                            ReleaseDate = new DateTime(2000, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 13,
                            AverageRating = 9.0999999999999996,
                            CoverImage = "show.jpg",
                            Description = "ovo je desc",
                            GroupType = 2,
                            ReleaseDate = new DateTime(2000, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Elen"
                        },
                        new
                        {
                            Id = 14,
                            AverageRating = 9.4000000000000004,
                            CoverImage = "show.jpg",
                            Description = "ovo je desc",
                            GroupType = 2,
                            ReleaseDate = new DateTime(2010, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Zvezde Granda"
                        },
                        new
                        {
                            Id = 15,
                            AverageRating = 8.0,
                            CoverImage = "show.jpg",
                            Description = "ovo je desc",
                            GroupType = 2,
                            ReleaseDate = new DateTime(2008, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Večera za 5"
                        },
                        new
                        {
                            Id = 16,
                            AverageRating = 8.9000000000000004,
                            CoverImage = "show.jpg",
                            Description = "ovo je desc",
                            GroupType = 2,
                            ReleaseDate = new DateTime(2015, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Potjera"
                        },
                        new
                        {
                            Id = 17,
                            AverageRating = 3.5,
                            CoverImage = "show.jpg",
                            Description = "ovo je desc",
                            GroupType = 2,
                            ReleaseDate = new DateTime(2013, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Zadruga"
                        },
                        new
                        {
                            Id = 18,
                            AverageRating = 8.5999999999999996,
                            CoverImage = "show.jpg",
                            Description = "ovo je desc",
                            GroupType = 2,
                            ReleaseDate = new DateTime(2005, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "How I Met Your Mother"
                        },
                        new
                        {
                            Id = 19,
                            AverageRating = 8.4000000000000004,
                            CoverImage = "show.jpg",
                            Description = "ovo je desc",
                            GroupType = 2,
                            ReleaseDate = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lupin"
                        },
                        new
                        {
                            Id = 20,
                            AverageRating = 9.6999999999999993,
                            CoverImage = "show.jpg",
                            Description = "ovo je desc",
                            GroupType = 2,
                            ReleaseDate = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "La Casa de Papel"
                        },
                        new
                        {
                            Id = 21,
                            AverageRating = 8.6999999999999993,
                            CoverImage = "show.jpg",
                            Description = "ovo je desc",
                            GroupType = 2,
                            ReleaseDate = new DateTime(2017, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Peaky Blinders"
                        },
                        new
                        {
                            Id = 22,
                            AverageRating = 9.9000000000000004,
                            CoverImage = "show.jpg",
                            Description = "ovo je desc",
                            GroupType = 2,
                            ReleaseDate = new DateTime(2013, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Naruto"
                        },
                        new
                        {
                            Id = 23,
                            AverageRating = 8.0999999999999996,
                            CoverImage = "show.jpg",
                            Description = "ovo je desc",
                            GroupType = 2,
                            ReleaseDate = new DateTime(2014, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kriza"
                        },
                        new
                        {
                            Id = 24,
                            AverageRating = 10.0,
                            CoverImage = "show.jpg",
                            Description = "ovo je desc",
                            GroupType = 2,
                            ReleaseDate = new DateTime(2008, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lud,zbunjen,normalan"
                        });
                });

            modelBuilder.Entity("ImdbAPI.Models.MediaActor", b =>
                {
                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<int>("ActorId")
                        .HasColumnType("integer");

                    b.HasKey("MediaId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("Cast");

                    b.HasData(
                        new
                        {
                            MediaId = 1,
                            ActorId = 4
                        },
                        new
                        {
                            MediaId = 1,
                            ActorId = 2
                        },
                        new
                        {
                            MediaId = 2,
                            ActorId = 4
                        },
                        new
                        {
                            MediaId = 2,
                            ActorId = 5
                        },
                        new
                        {
                            MediaId = 3,
                            ActorId = 6
                        },
                        new
                        {
                            MediaId = 3,
                            ActorId = 8
                        },
                        new
                        {
                            MediaId = 4,
                            ActorId = 1
                        },
                        new
                        {
                            MediaId = 4,
                            ActorId = 5
                        },
                        new
                        {
                            MediaId = 5,
                            ActorId = 7
                        },
                        new
                        {
                            MediaId = 5,
                            ActorId = 8
                        },
                        new
                        {
                            MediaId = 6,
                            ActorId = 9
                        },
                        new
                        {
                            MediaId = 6,
                            ActorId = 10
                        },
                        new
                        {
                            MediaId = 7,
                            ActorId = 3
                        },
                        new
                        {
                            MediaId = 7,
                            ActorId = 7
                        },
                        new
                        {
                            MediaId = 8,
                            ActorId = 3
                        },
                        new
                        {
                            MediaId = 8,
                            ActorId = 4
                        },
                        new
                        {
                            MediaId = 9,
                            ActorId = 1
                        },
                        new
                        {
                            MediaId = 9,
                            ActorId = 10
                        },
                        new
                        {
                            MediaId = 10,
                            ActorId = 9
                        },
                        new
                        {
                            MediaId = 10,
                            ActorId = 5
                        },
                        new
                        {
                            MediaId = 11,
                            ActorId = 7
                        },
                        new
                        {
                            MediaId = 11,
                            ActorId = 3
                        },
                        new
                        {
                            MediaId = 12,
                            ActorId = 2
                        },
                        new
                        {
                            MediaId = 12,
                            ActorId = 1
                        },
                        new
                        {
                            MediaId = 13,
                            ActorId = 6
                        },
                        new
                        {
                            MediaId = 13,
                            ActorId = 7
                        },
                        new
                        {
                            MediaId = 14,
                            ActorId = 3
                        },
                        new
                        {
                            MediaId = 14,
                            ActorId = 6
                        },
                        new
                        {
                            MediaId = 15,
                            ActorId = 9
                        },
                        new
                        {
                            MediaId = 15,
                            ActorId = 2
                        },
                        new
                        {
                            MediaId = 16,
                            ActorId = 1
                        },
                        new
                        {
                            MediaId = 16,
                            ActorId = 3
                        },
                        new
                        {
                            MediaId = 17,
                            ActorId = 5
                        },
                        new
                        {
                            MediaId = 17,
                            ActorId = 10
                        },
                        new
                        {
                            MediaId = 18,
                            ActorId = 4
                        },
                        new
                        {
                            MediaId = 18,
                            ActorId = 8
                        },
                        new
                        {
                            MediaId = 19,
                            ActorId = 9
                        },
                        new
                        {
                            MediaId = 19,
                            ActorId = 4
                        },
                        new
                        {
                            MediaId = 20,
                            ActorId = 1
                        },
                        new
                        {
                            MediaId = 20,
                            ActorId = 2
                        },
                        new
                        {
                            MediaId = 21,
                            ActorId = 1
                        },
                        new
                        {
                            MediaId = 21,
                            ActorId = 7
                        },
                        new
                        {
                            MediaId = 22,
                            ActorId = 8
                        },
                        new
                        {
                            MediaId = 22,
                            ActorId = 2
                        },
                        new
                        {
                            MediaId = 23,
                            ActorId = 5
                        },
                        new
                        {
                            MediaId = 23,
                            ActorId = 3
                        },
                        new
                        {
                            MediaId = 24,
                            ActorId = 7
                        },
                        new
                        {
                            MediaId = 24,
                            ActorId = 9
                        });
                });

            modelBuilder.Entity("ImdbAPI.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<int>("StarRating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MediaId = 1,
                            StarRating = 7
                        },
                        new
                        {
                            Id = 2,
                            MediaId = 1,
                            StarRating = 7
                        },
                        new
                        {
                            Id = 3,
                            MediaId = 2,
                            StarRating = 6
                        },
                        new
                        {
                            Id = 4,
                            MediaId = 2,
                            StarRating = 9
                        },
                        new
                        {
                            Id = 5,
                            MediaId = 3,
                            StarRating = 2
                        },
                        new
                        {
                            Id = 6,
                            MediaId = 3,
                            StarRating = 7
                        },
                        new
                        {
                            Id = 7,
                            MediaId = 4,
                            StarRating = 5
                        },
                        new
                        {
                            Id = 8,
                            MediaId = 4,
                            StarRating = 9
                        },
                        new
                        {
                            Id = 9,
                            MediaId = 5,
                            StarRating = 1
                        },
                        new
                        {
                            Id = 10,
                            MediaId = 5,
                            StarRating = 7
                        },
                        new
                        {
                            Id = 11,
                            MediaId = 6,
                            StarRating = 8
                        },
                        new
                        {
                            Id = 12,
                            MediaId = 6,
                            StarRating = 9
                        },
                        new
                        {
                            Id = 13,
                            MediaId = 7,
                            StarRating = 2
                        },
                        new
                        {
                            Id = 14,
                            MediaId = 7,
                            StarRating = 9
                        },
                        new
                        {
                            Id = 15,
                            MediaId = 8,
                            StarRating = 4
                        },
                        new
                        {
                            Id = 16,
                            MediaId = 8,
                            StarRating = 8
                        },
                        new
                        {
                            Id = 17,
                            MediaId = 9,
                            StarRating = 6
                        },
                        new
                        {
                            Id = 18,
                            MediaId = 9,
                            StarRating = 9
                        },
                        new
                        {
                            Id = 19,
                            MediaId = 10,
                            StarRating = 6
                        },
                        new
                        {
                            Id = 20,
                            MediaId = 10,
                            StarRating = 9
                        },
                        new
                        {
                            Id = 21,
                            MediaId = 11,
                            StarRating = 6
                        },
                        new
                        {
                            Id = 22,
                            MediaId = 12,
                            StarRating = 9
                        },
                        new
                        {
                            Id = 23,
                            MediaId = 13,
                            StarRating = 4
                        },
                        new
                        {
                            Id = 24,
                            MediaId = 14,
                            StarRating = 7
                        },
                        new
                        {
                            Id = 25,
                            MediaId = 15,
                            StarRating = 9
                        },
                        new
                        {
                            Id = 26,
                            MediaId = 16,
                            StarRating = 8
                        },
                        new
                        {
                            Id = 27,
                            MediaId = 17,
                            StarRating = 1
                        },
                        new
                        {
                            Id = 28,
                            MediaId = 18,
                            StarRating = 3
                        },
                        new
                        {
                            Id = 29,
                            MediaId = 19,
                            StarRating = 5
                        },
                        new
                        {
                            Id = 30,
                            MediaId = 20,
                            StarRating = 9
                        },
                        new
                        {
                            Id = 31,
                            MediaId = 21,
                            StarRating = 4
                        },
                        new
                        {
                            Id = 32,
                            MediaId = 22,
                            StarRating = 9
                        },
                        new
                        {
                            Id = 33,
                            MediaId = 23,
                            StarRating = 6
                        },
                        new
                        {
                            Id = 34,
                            MediaId = 24,
                            StarRating = 9
                        });
                });

            modelBuilder.Entity("ImdbAPI.Models.MediaActor", b =>
                {
                    b.HasOne("ImdbAPI.Models.Actor", "Actor")
                        .WithMany("Cast")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImdbAPI.Models.Media", "Media")
                        .WithMany("Cast")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("ImdbAPI.Models.Rating", b =>
                {
                    b.HasOne("ImdbAPI.Models.Media", "Media")
                        .WithMany("Ratings")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("ImdbAPI.Models.Actor", b =>
                {
                    b.Navigation("Cast");
                });

            modelBuilder.Entity("ImdbAPI.Models.Media", b =>
                {
                    b.Navigation("Cast");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
